-- Добавление данных в таблицу RATING
INSERT INTO PUBLIC.RATING (RATING) VALUES ('G');
INSERT INTO PUBLIC.RATING (RATING) VALUES ('PG');
INSERT INTO PUBLIC.RATING (RATING) VALUES ('PG-13');
INSERT INTO PUBLIC.RATING (RATING) VALUES ('R');
INSERT INTO PUBLIC.RATING (RATING) VALUES ('NC-17');
