-- PUBLIC.RATING definition

-- Drop table

-- DROP TABLE PUBLIC.RATING;

CREATE TABLE IF NOT EXISTS PUBLIC.RATING (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	RATING VARCHAR_IGNORECASE(10) NOT NULL,
	CONSTRAINT RATING_PK PRIMARY KEY (ID)
);